---
- name: Destroy the Kerberos ticket cache
  ansible.builtin.command: kdestroy -A
  changed_when: false
  failed_when: false

- name: Remove the transient keytab directory
  ansible.builtin.file:
    path: "{{ dual_auth_tmp_keytab_path | dirname }}"
    state: absent
  no_log: true
  when: dual_auth_tmp_keytab_path is defined
