---
- name: Destroy the Kerberos ticket cache
  ansible.builtin.command: kdestroy -A
  changed_when: false
  failed_when: false

- name: Remove the transient keytab directory
  ansible.builtin.file:
    path: "{{ mrg_dual_auth_keytab_tmpdir.path }}"
    state: absent
  no_log: true
  when: mrg_dual_auth_keytab_tmpdir is defined
