passwd:     files sss systemd  {exclude if "with-custom-passwd"}
group:      files sss systemd  {exclude if "with-custom-group"}
netgroup:   files sss          {exclude if "with-custom-netgroup"}
automount:  files          {exclude if "with-custom-automount"}
services:  files          {exclude if "with-custom-services"}
sudoers:    files          {include if "with-sudo"}
